### ISSUE TITLE
Multi uploads

### ISSUE THREAD

**Issue by userino666** [codingjoe/django-stdimage#198]
Hello  cant understand how to save multi images. With default ImageField i can do this 
                for f in imgs:
                    model.file.create(file=f)
but with stdimage i get error that
'StdImageFieldFile' object has no attribute 'create'

**Comment by codingjoe** [comment]
Hi @userino666 sorry for the late response.
I am fairly certain that you have a tiny bug in your code. Please try:
```python
model.objects.create(file=f)
```

I am fairly certain that your code also wouldn't work with a regular FileField, since this package inherits the default behavior.

I hope my example helped you. Let me know if I can be of any other help.

Best
-Johannes
