### ISSUE TITLE
How to deal with upload_to deprecations ?

### ISSUE THREAD

**Issue by olymk2** [codingjoe/django-stdimage#202]
In this commit upload_to has been deprecated it suggests using django-dynamic-filenames.

how would I change the below code to use django-dynamic-filenames might be worth documenting this as other will likely hit the issue when they upgrade, I may just downgrade for now but it would be good to know how I should integrate django-djanamic-filnames in a way that maintains my current filenames and paths.

    image = StdImageField(
        upload_to=UploadToAutoSlugClassNameDir(populate_from="title"),
        blank=True,
        null=True,
        variations=image_variations,
    )

**Comment by codingjoe** [comment]
Hi @olymk2, thanks for reaching out. This is a good question. Maybe I could add more examples.
Your case should be solved using the following pattern:

```python
upload_to_pattern = FilePattern(
    filename_pattern='{model_name}/{instance.title:slug}{ext}'
)
```

If you have more questions, feel free to ask.

Best
-Joe

**Comment by jmaslanka** [comment]
Ran into this "obstacle" as well, changing `UploadTo...` wasn't a problem but these functions were referenced in migrations so another thing to take care of (I also ran into import errors along the way lol).

In my opinion it was best to leave them and mark them as depreciated, just to have backwards compatibility. No harm done to package itself but might save others some time.

**Comment by codingjoe** [comment]
@jmaslanka I wasn't anticipating that many people using this feature. I still want to make sure to keep debt low for this package. Deprecation only makes sense if you have release cycles, which this small package does not. Version number clearly indicates a breaking change and the release notes describe what has changed. I understand that it is not super convenient, but that's the nature of breaking changes :/

Regarding your problem. I would suggest to simply change your old migrations or to backport the old upload to utils if you want to go all fancy. I don't see a need for the latter option tho, because the `upload_to` is not db schema relevant.
