### ISSUE TITLE
Option for Base64 variation.

### ISSUE THREAD

**Issue by jckw** [codingjoe/django-stdimage#212]
Is there a simple way to extend the StdImageField to support a variation that returns a base 64 string as the "rendered" version?

I'm thinking of settings such that you could do this: 

```
image = StdImageField(
    upload_to='path/to/img',
    variations={
        "tinyB64": {
            "width": 50,
            "height": 50,
            "crop": True,
            "asBase64": True
        }
    }
)
```

I guess instead of returning an ImageFileDescriptor for variation, a CharField would be returned instead?

This would be an amazing feature to add to this already great lib!

**Comment by codingjoe** [comment]
Hi @jckw thanks for reaching out. That is an excellent question. Since I assume you want to "render" the base64 encoded file in an HTML template, a template tag might serve you better.

I haven't tested the following code, but the general idea should work. Maybe give it a spin and reach out to me if it works or if you need any help. Maybe we could make this template tag part of the library. That would be a cool feature.

Best
-Joe

```python
import os

from django import template

register = template.Library()

@register. simple_tag
def encode_static(file):
    encoded_string = base64.b64encode(file.read())
    _, ext = os.path.splitext(file.name)
    return f'data:image/{ext};base64,{encoded_string}'
```

**Comment by jckw** [comment]
Thanks for getting back to me so fast @codingjoe! 

Actually, I’m using StdImage as part of a GraphQL API, but I think the idea is still valid. 

Since base64 encoding is unlikely to be a bottleneck, I can just calculate it on each request.

I was more wondering whether it would be possible to calculate it once and save it, however this seems like a good enough solution!

**Comment by codingjoe** [comment]
Hi @jckw,

I see, this is an even better question. Let me elaborate a bit. I understand the idea in GraphQL is, to be able to fetch as many data in a single request as possible. This notion is driven by the fact that in mobile (3/4G) connections latency is usually high as is bandwidths.
It is true that encoding a binary file on the fly from binary to base64 doesn't case much CPU load, most grinding is done in `binascii`, which is written in C.
BUT, this method might cause unwanted IO. Especially if you use Django in a traditional synchronous way, this IO will simply cause your thread to wait for IO instead of performing CPU tasks. If you are using the storage of your application server this is fine, since the file systems and hard drives usually are pretty good at caching, if you are using an external storage however, like AWS S3 or an ISCSI rig, this will be a problem. It is usually preferable that your application server does not serve large binary data, but you have an HTTP CRUD storage like S3 serving it directly to the user or via a CDN as a proxy.

You should also consider that adding binary data all into a single request prevents the data from being cached by your browser or a proxy. So if you need to serve data on multiple sites, you might want have that extra request, since it will only be performed once and then never again until the cache expires.

One last thing to consider is size. In case bandwidth is low, sending binary data uncompressed and base64 encoded will result in large responses. Usually you gzip or brotli compress static assets, which will result in much smaller HTTP bodies.

My advice:
* Use inline SVGs where possible using `{% include 'my.svg' %}` over `{% static 'my.svg' %}`. 
* Use [whitenoise](http://whitenoise.evans.io/en/stable/) by @evansd (he know is sh*t) and install `brotli` too
* Use an HTTP CRUD file storage like AWS S3 or Google Cloud Storage for large files.
* Add a multi location CDN if you care about the last global network latency and have plenty cash ;)

One last thing, the idea of this library is not to prevent application server IO and on the fly resizing. We use the lanczos algorithm by default, which is slow but yields very good results. By precompiling all file sizes and storing them on an external storage, we can server millions of images without much load on the application server. If you ever want to build your own Instagram, this might be the way to go ;)

I hope that helps you a bit. Let me know if you have any further questions.

Best
-Joe

**Comment by jckw** [comment]
Those are all great points @codingjoe! Thanks so much for the full response. Definitely didn't think about the caching aspect like this before (although GraphQL clients can usually handle this aspect since all the components are loaded at once so the cached base64 is loaded at the same time as image components).

Again, thanks for all this detail! Super useful.
