### ISSUE TITLE
render_variations() call not working in Migrations

### ISSUE THREAD

**Issue by chgad** [codingjoe/django-stdimage#280]
Hi,

i'm switching to the StdImage from a simple ImageFiled.

I'm calling `instance.img.render_variations()` during the data migration but the variations are missing afterwards.

However, if i enter the django shell, fetch the same instance and execute `instance.img.render_variations()` all variations are created.

What is going wrong here (except the obvious)?

**Comment by codingjoe** [comment]
Hi @chgad,

Thank you for reaching out. I am planing a new WebP and AVIF field as a new feature for this package. I will use the opportunity to check how migrations work. I believe the expected behavior would be, that the migrations are created automatically, when you add the field or a change the variations' config, right?

Best,
Joe

**Comment by chgad** [comment]
Yes, that's waht i would expect.

A small addition:
We also ahve a "Meta" Modell for our Images for which we are switchingover to StdImageField and inside the Data migration we create new Model-Instances "by hand" from old, already existing images. In this case also no variations are created automatically and the above hack has to be apllied.

**Comment by codingjoe** [comment]
Hi @chgad, I've been very busy working on a successor to this package, based on modern web standards. I am currently working on the migration feature: https://github.com/codingjoe/django-pictures/pull/3
Maybe give it a spin? It's still in alpha, but with your help, we can get a stable release sooner.

I will close the issue here for now.
